"use client";
import { useEffect, useState } from "react";

export default function EncouragementBanner() {
  const [message, setMessage] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [isDismissed, setIsDismissed] = useState(false);

  useEffect(() => {
    async function generateMessage() {
      try {
        const res = await fetch("/api/encouragement", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
        });
        const data = await res.json();
        setMessage(data.message || "Keep up the great work with your nutrition goals!");
      } catch (error) {
        setMessage("You're doing great with your nutrition journey!");
      } finally {
        setLoading(false);
      }
    }

    generateMessage();
  }, []);

  if (loading) {
    return (
      <div className="w-full bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 border-b border-blue-200 dark:border-blue-800">
        <div className="w-full px-6 sm:px-10 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-300">
              <span className="animate-pulse">✨</span>
              <span>Generating encouragement...</span>
            </div>
            <button
              onClick={() => setIsDismissed(true)}
              className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 transition-colors"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (isDismissed) {
    return null;
  }

  return (
    <div className="w-full bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 border-b border-blue-200 dark:border-blue-800">
      <div className="w-full px-6 sm:px-10 py-3">
        <div className="flex items-start justify-between gap-2">
          <div className="flex items-start gap-2 flex-1">
            <span className="text-lg">✨</span>
            <div className="flex-1">
              <p className="text-sm text-gray-700 dark:text-gray-200 leading-relaxed">
                {message}
              </p>
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                Generated by AI
              </p>
            </div>
          </div>
          <button
            onClick={() => setIsDismissed(true)}
            className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 transition-colors flex-shrink-0 mt-0.5"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
}
