"use client";
import { useEffect, useState } from "react";

export default function EncouragementBanner() {
  const [message, setMessage] = useState<string>("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function generateMessage() {
      try {
        const res = await fetch("/api/encouragement", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
        });
        const data = await res.json();
        setMessage(data.message || "Keep up the great work with your nutrition goals!");
      } catch (error) {
        setMessage("You're doing great with your nutrition journey!");
      } finally {
        setLoading(false);
      }
    }

    generateMessage();
  }, []);

  if (loading) {
    return (
      <div className="w-full bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 border-b border-blue-200 dark:border-blue-800">
        <div className="w-full px-6 sm:px-10 py-3">
          <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-300">
            <span className="animate-pulse">✨</span>
            <span>Generating encouragement...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 border-b border-blue-200 dark:border-blue-800">
      <div className="w-full px-6 sm:px-10 py-3">
        <div className="flex items-start gap-2">
          <span className="text-lg">✨</span>
          <div className="flex-1">
            <p className="text-sm text-gray-700 dark:text-gray-200 leading-relaxed">
              {message}
            </p>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
              Generated by AI
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
